In [ ]:
'''
约瑟夫问题
'''

def move(man,sep):
    '''
    man list leftwards move to sep units, the first element on the left added to the tail of the list.
    '''
    for i in range(sep):
        item = man.pop(0)
        man.append(item)

def play(man,seq,rest):
    '''
    man = men count
    seq = sequence to kill
    rest = survivors number
    
    '''
    print('{}men in total, the {}rd one will be eliminated, survivors are {}'.format(man,seq,rest))
    man = [i for i in range(1,man+1)]
    seq -= 1
    while len(man)>rest:
        move(man,seq)
        print('eliminated', man.pop(0))
    return man
survivor = play(41,3,2)
print(survivor)

In [ ]:
'''Map,filter,reduce'''
from functools import reduce
s= [1,2,3]
k= map(lambda x:x+1,s)
print(list(k))

l = filter(lambda x:x%3,s)
print(list(l))

r = reduce(lambda x,y:x+y,[1,2,3])
print(list(r))

In [ ]:
class PubAndPri:
    pub = "this is public"
    __pri = "this is private"
    
    def __init__(self):
        self.other = "pub variable can be created "
    def out_pub(self):
        print("public method", self.pub , self.__pri)
    def __out_pri(self):
        print("private method", self.pub, self.__pri)

pp = PubAndPri()
pp.out_pub()
print(pp.pub, pp.other)
try:
    pp.out_pri()
except Exception as e:
    print("use private func has error")
finally:
    print()
try:
    print(pp.__pri)
except Exception as e:
    print("use private variable has error")
finally:
    print()

### 2.5 数据分析
#### 2.5.1 重复值处理 drop_duplicates(self,subset,keep)

In [ ]:
import pandas as pd
df = pd.DataFrame({'age':pd.Series([26,85,64,85,85]),
                   'name':pd.Series(['Ben','John','Jerry','John','John'])})
df.iloc[1,1]='Johns'
df.iloc[4,1]='Eric'
df
df_dedup = df.drop_duplicates(['age'],keep='last')
df_dedup

#### 2.5.2 缺失值处理
- 缺失数据的查找，用isnull,notnull,isna,notna

In [ ]:
df = pd.DataFrame({'age':pd.Series([26,85,64,85,85]),
                   'name':pd.Series(['Ben','John ',' Jerry ',' John','John'])})
df.iloc[1,1]=None
#df.iloc[0,2]=NA
df.notnull()
df.isnull()

- 缺失数据处理:
    - dropna() 去除数据为空对应行 how='any','all',axis = 0/1
    - df.fillna()

In [ ]:
#df.dropna(how='age')
df.iloc[1,1]=None
df.fillna(method='bfill')#后一个数据填充
df.fillna(method='pad')#前一个数据填充
df.fillna(df.mean())#用平均值填充

In [ ]:
import numpy as np

df = pd.DataFrame(np.random.randint(0,10,(1,36)).reshape((6,6)),index = ['A','B','C','D','E','F'])

df

In [ ]:
import pandas as pd
import numpy
#字段抽取 指定位置截取
df['age']= df['age'].astype(str)
generation  = df['age'].str.slice(0,1) # 字符串str（）
generation

In [ ]:
#字段拆分
#split(sep,n,expand=False)
#sep是分隔符
#n是新增列数量
#expand 是否展开成数据框
purchase_1 = pd.Series({'Name': 'Chris',
                        'Item Purchased': 'Dog Food',
                        'Cost': 22.50})
purchase_2 = pd.Series({'Name': 'Kevyn',
                        'Item Purchased': 'Kitty Litter',
                        'Cost': 2.50})
purchase_3 = pd.Series({'Name': 'Vinod',
                        'Item Purchased': 'Bird Seed',
                        'Cost': 5.00})

df = pd.DataFrame([purchase_1,purchase_2,purchase_3],index = range(1,4))
df
words = df['Item Purchased'].str.split(" ",1,True)
words

In [ ]:
#基于一定条件记录抽取
'''
df[condition]
compare
scope between[min,max]
null pandas.isnull(column)
character match: str.contains(pattern,na=False),e.g. df[df.title.str.contains('radio'),na=False]
logic : & | not

'''

In [ ]:
'''
df.loc[rowlabel,columnlabel]
如果两个参数都是列表，返回的是DataFrame，反之是series

'''
df.loc[1:3,:]

In [ ]:
'''
df.iloc[rowindexnumber,columnindexnumber]
iloc = integer location

'''

In [ ]:
'''
字典数据抽取

'''
# key value as different columns
import pandas as pd
d1 = {'a':'[1,2,3]','b':'[0,1,2]'}
a1 = pd.DataFrame.from_dict(d1, orient='index')
a1.index.name = 'key'
b1= a1.reset_index()
b1.columns= ['key','value']
b1

In [ ]:
# every element in the dict as one column( same length)
d2 = {'a':[1,2,3],'b':[4,5,6]}
a2 = pd.DataFrame(d2)
a2

In [ ]:
# every element in the dict as one column(different length)
d={'one':pd.Series([1,2,3]),
   'two':pd.Series([1,2,3,4])}
df = pd.DataFrame(d)
df

In [ ]:
#use np.array as dict element
import numpy as np

d = dict(A=np.array([1,2]),B=np.array([1,2,3,4]))
 
df = pd.DataFrame(dict([(k,pd.Series(v)) for k,v in d.items()]))
df

a=dict([(k,pd.Series(v)) for k,v in d.items()])
a

In [ ]:
for k,v in d.items():
    print(k,pd.Series(v))
    print(type(k))
    print(type(v))
    print(type(pd.Series(v)))

In [ ]:
my_dict = dict(A=np.array([1,2]),B=np.array([1,2,3,4]))
df = pd.DataFrame.from_dict(my_dict,orient='index').T
df

In [ ]:
### insert record in pandas

df = pd.DataFrame({'a':[1,2,3],'b':['a','b','c'],'c':['A','B','C']})
df
line = pd.DataFrame({df.columns[0]:"--",
                    df.columns[1]:"--",
                    df.columns[2]:"--"},
                   index=[1])
df0 = pd.concat([df.loc[:0],line,df.loc[1:]])
df

In [ ]:
df0

In [ ]:
df1=df0.reset_index(drop=True)
df1

In [ ]:
from pandas import read_excel
df = pd.read_excel('sourcedata/i_nuc.xls',sheet_name='Sheet3')
df
df2 = df.loc[:,'英语']
df2
randScore = np.random.randint(0,100,21)
randScore
df3= df
df['英语']=pd.Series(randScore)
type(df.loc[0,'体育'])
type(df.loc[0,'英语'])
type(pd.Series(randScore).loc[0])
df  # 如果用外界数据替换datafram中的数据，如果有缺失值，则导入的数据会自动转成float

In [ ]:
df4=df.replace({'作弊':'缺考'})
df4

In [ ]:
#df.replace
#Series对象值替换
s = df.iloc[2]#获取行索引为2数据
#单值替换
s.replace('?',np.nan)#用np.nan替换？
s.replace({'?':'NA'})#用NA替换？
#多值替换
s.replace(['?',r'$'],[np.nan,'NA'])#列表值替换
s.replace({'?':np.nan,'$':'NA'})#字典映射
#同缺失值填充方法类似
s.replace(['?','$'],method='pad')#向前填充
s.replace(['?','$'],method='ffill')#向前填充
s.replace(['?','$'],method='bfill')#向后填充
#limit参数控制填充次数
s.replace(['?','$'],method='bfill',limit=1)
#DataFrame对象值替换
#单值替换
df.replace('?',np.nan)#用np.nan替换？
df.replace({'?':'NA'})#用NA替换？
#按列指定单值替换
df.replace({'EMPNO':'?'},np.nan)#用np.nan替换EMPNO列中?
df.replace({'EMPNO':'?','ENAME':'.'},np.nan)#用np.nan替换EMPNO列中?和ENAME中.
#多值替换
df.replace(['?','.','$'],[np.nan,'NA','None'])##用np.nan替换？用NA替换. 用None替换$
df.replace({'?':'NA','$':None})#用NA替换？ 用None替换$
df.replace({'?','$'},{'NA',None})#用NA替换？ 用None替换$
#正则替换
df.replace(r'\?|\.|\$',np.nan,regex=True)#用np.nan替换？或.或$原字符
df.replace([r'\?',r'\$'],np.nan,regex=True)#用np.nan替换？和$
df.replace([r'\?',r'\$'],[np.nan,'NA'],regex=True)#用np.nan替换？用NA替换$符号
df.replace(regex={r'\?':None})
#value参数显示传递
df.replace(regex=[r'\?|\.|\$'],value=np.nan)#用np.nan替换？或.或$原字符

In [ ]:
###交换行或者列
df = pd.DataFrame({'a':[1,2,3],
                   'b':['a','b','c'],
                   'c':['A','B','C']})
df
hang= [0,2,1]
df.reindex(hang) # 行交换
lie = ['a','c','b']
df.reindex(columns =lie) #列交换

In [ ]:
df = pd.DataFrame({'a':[1,2,3],
                   'b':['a','b','c'],
                   'c':['A','B','C']})
print(df.loc[[0,2],:])
#df.loc[[0,2],:]=df.loc[[2,0],:].values #0,2 two row swap
#df
df.loc[:,['a','b']]=df.loc[:,['b','a']].values # two columns swap
df
#### notes: just change the value of the row or column, not the index

In [ ]:
name = list(df.columns)
i = name.index("a")
j = name.index("b")
print(i,j)
name[i],name[j]=name[j],name[i]
print(name)
df.columns= name  
df

In [ ]:
df['d']=range(len(df.index))
df

In [ ]:
import pandas as pd

df0={'Ohio':[0,6,3],
     'Texas':[7,4,1],
     'Califonia':[2,8,5]}
df=pd.DataFrame(df0,index=['c','d','a'])
df1=df.sort_values(by='Texas',ascending=True)
print(df)
print(df1)

In [ ]:
ser = pd.Series([3,2,0,3],index = list('abcd'))
ser.rank()
print(ser)
print(ser.rank())
print(ser.rank(method='min'))
print(ser.rank(method='max'))
print(ser.rank(method='average'))
print(ser.rank(method='first'))

In [ ]:
df = pd.DataFrame({'a':[1,2,3,0],'c':["A","E","B","C"],
                   'd':['a','b','d','c'],
                   'b':[1,3,2,5]},index=[1,3,2,4])
df1=df.sort_index(axis = 1)
df2=df.sort_index(axis = 0)
#print(df1)
#print("____"*10)
#print(df2)

print(df)
print(df.sort_values(['c','b']))

In [ ]:
df =pd.Series(['a','d','c','b'],index = [1,2,4,3])
print(df)
import numpy as np
A=[3,4,1,2,5]
B=[]
print(A)
df1=df.reindex(A).ffill()# method 为ffill要求索引先按一定顺序排列
print(df1)

## reindex will return a new object which the index strictly follows the input
## method = {'backfill','bfill','pad','ffill','None'} ffill = pad, backfill = bfill
# reindex is used to change the index instead of the values, if the new index is not exist before, 
# values of this idnex will be set to NAN or None, the original value won`t be changed.

In [ ]:
df = pd.DataFrame(np.arange(9).reshape((3,3)),index = ['a','d','b'],columns=['x','y','z'])

df1 = df.reindex(index = ['b','d','a','c'])
print(df)

print(df1)
df1.loc['c']=[10,11,12]
print(df1)
df2 = df.reindex(columns = list('yzx'))
df3 = df.reindex(columns = ['y','z','w'])

print(df2)
print(df3)
df4=df3.fillna(method='ffill',axis = 1)
print(df3)

print(df4)

In [ ]:
### set index
df = pd.DataFrame({'a':[1,2,3],'b':list('abc'),'c':list("ABC")})
df2 = df.set_index(['b','c'],
             drop=False, # 是否扔掉index列
             append = True,# 是否保留原索引
            inplace = False)# 是否在原df上改变
print(df)
print(df2)

In [ ]:
# reset_index()
df=pd.DataFrame({'a':range(1,4),'b':list('abc'),'c':list('ABC')})
df1= df.set_index(['b','c'],drop = False, append= True,inplace = False)
df1
df2 = df1.reset_index(level='b',drop= True)
print(df1)
print(df2)

In [ ]:
## data combine

#concat([df1,df2]) # structure should be the same for df1, df2
df1 = pd.read_excel('sourcedata/i_nuc.xls',sheet_name='Sheet3')
df1
df2 = pd.read_excel('sourcedata/i_nuc.xls',sheet_name='Sheet5')
df2
#print(df1)
#print(df2)
df= pd.concat([df1,df2])# index won`t increase
print(df)

In [ ]:
df= df.astype(str)
tel=df['姓名']+'&'+df['学号']
tel

In [ ]:
df1 = pd.read_excel('sourcedata/i_nuc.xls',sheet_name='Sheet3')
print(df1.head())
df2 = pd.read_excel('sourcedata/i_nuc.xls',sheet_name='Sheet4')
print(df2.head())
df = pd.merge(df1,df2,left_on='学号',right_on='学号')
print(df.head())

In [ ]:
# 2.8.2 数据标准化

'''
1. min-max标准化(min-max normalization)
离差标准化 x = (x-max)/(max-min)
'''
df = pd.read_excel('sourcedata/i_nuc.xls',sheet_name='Sheet3')
df.head()
scale=(df.数分.astype(int)-df.数分.astype(int).min())/(df.数分.astype(int).max()-df.数分.astype(int).min())
scale.head()

In [ ]:
'''
2. Z-score 标准化方法
属性A的最值未知的情况，基于原始数据的标准差和均值进行数据标准化
X = (x-μ)/σ

'''
from sklearn import preprocessing
import numpy as np

df1=df['数分']
df_scaled = preprocessing.scale(df1)
df_scaled

'''
sklearn.preprocessing.StandardScaler 类，使用该类可以保存训练集中的参数（均值，标准差），直接使用其对象转换测试数据集
                                                                                                                                                       
'''
X= np.array([[1,-1,2],
           [2,0,0],
           [0,1,-1]],dtype= float)

scaler = preprocessing.StandardScaler().fit(X) #用训练集计算出标准差和均值
print(scaler.mean_)
print(scaler.scale_)

scaler.transform(X)# 用该训练集的标准差和均值处理测试集数据

In [ ]:
### 2.5.9数据分组
import pandas as pd
import numpy as np
#pd.cut(series, bins,right=True,labels=NULL)
'''
series 需要分组的数据
bins 分组依据的书
right 分组是否右闭合
labels 分组自定义标签
'''
df = pd.read_excel('sourcedata/rz.xlsx')
df.shape

In [ ]:
bins=[min(df.解几)-1,60,70,80,max(df.解几)+1]# 留出最高最低,建议先求出最大最小值然后再分段
lab=["不及格","及格","良好","优秀"]
demo = pd.cut(df.解几,bins,right=False,labels=lab)
demo.head()
df['demo']=demo
df.head()

In [ ]:
### 2.5.10 日期处理
#1. 日期转换
'''
to_datatime()

'''
df = pd.read_csv('sourcedata/rz3.csv',sep=',',encoding='utf8')
df
df_dt = pd.to_datetime(df.date,format='%Y/%m/%d')
df_dt

In [ ]:
###
#2.日期格式化将日期型的 to str
#.apply可以对整个dataframe内所有数据或某些数据进行统一处理
df_dt_str = df_dt.apply(lambda x: pd.datetime.strftime(x,"%Y/%m/%d"))
# apply(axis=0)按列，axis=1按行运算

In [ ]:
df_dt_str

In [ ]:
df=pd.DataFrame({'ohio':[1,3,6],
                 'texas':[1,4,5],
                 'california':[2,5,8]},
                index = list('acd'))
print(df)
f = lambda x : x.max()-x.min()
# apply(axis=0)按列，axis=1按行运算
print(df.apply(f)) #默认按列运算；(2,0)-(0,0) , (2,1)-(0,1), (2,2)-(0,2)
print(df.apply(f,axis=1))

In [ ]:
#date extraction
#date_dt.dt.property
type(df_dt.dt)
print(df_dt.dt,df_dt.dt.day)

In [137]:
## data process example

import pandas as pd 
#读取数据
df = pd.read_excel('sourcedata/rz.xlsx')
#print(df.shape)

#去除重复
df1=df.drop_duplicates()
#print(df1)
df1.iloc[:,4:10]
#更换非法值
df1=df1.replace({"作弊":0,
             "缺考":0})
#填入空值
df1=df1.fillna(0)

#去除空格
df0 = df1.copy()
for course in list(df0.columns):
    df0.loc[:,course].astype(str).map(str.strip)
#print(df0)
#print(df0.columns)
#print(list(df0.columns))
#查看列数据类型
for i in list(df0.columns):
    if df0[i].dtype=="O":
        print(i)

姓名
性别
姓名
性别

In [148]:
df1['score']=df1.loc[:,['英语','体育','军训','数分','高代','解几']].astype(int).sum(axis=1)
#df1.isnull().any() 判断哪一列有空值
bins=[min(df1.score)-1,400,450,max(df1.score)+1]# 留出最高最低,建议先求出最大最小值然后再分段
lab=["一般","较好","优秀"]
demo = pd.cut(df1.score,bins,right=False,labels=lab)
df1['类别']=demo
df1

            学号        班级   姓名 性别  英语  体育    军训  数分  高代  解几  score  类别
0   2308024241  23080242   成龙  男  76  78  77.0  40  23  60    354  一般
1   2308024244  23080242   周怡  女  66  91  75.0  47  47  44    370  一般
2   2308024251  23080242   张波  男  85  81  75.0  45  45  60    391  一般
3   2308024249  23080242   朱浩  男  65  50  80.0  72  62  71    400  较好
4   2308024219  23080242   封印  女  73  88  92.0  61  47  46    407  较好
5   2308024201  23080242   迟培  男  60  50  89.0  71  76  71    417  较好
6   2308024347  23080243   李华  女  67  61  84.0  61  65  78    416  较好
7   2308024307  23080243   陈田  男  76  79  86.0  69  40  69    419  较好
8   2308024326  23080243   余皓  男  66  67  85.0  65  61  71    415  较好
9   2308024320  23080243   李嘉  女  62   0  90.0  60  67  77    356  一般
10  2308024342  23080243  李上初  男  76  90  84.0  60  66  60    436  较好
11  2308024310  23080243   郭窦  女  79  67  84.0  64  64  79    437  较好
12  2308024435  23080244  姜毅涛  男  77  71   0.0  61  73  76    358  一般
13  2308024432  23080244   赵宇  男  74  74  88.0  68  70  71    445  较好
14  2308024446  23080244   周路  女  76  80   0.0  61  74  80    371  一般
15  2308024421  23080244  林建祥  男  72  72  81.0  63  90  75    453  优秀
16  2308024433  23080244  李大强  男  79  76  77.0  78  70  70    450  优秀
17  2308024428  23080244  李侧通  男  64  96  91.0  69  60  77    457  优秀
18  2308024402  23080244   王慧  女  73  74  93.0  70  71  75    456  优秀
19  2308024422  23080244  李晓亮  男  85  60  85.0  72  72  83    457  优秀

In [195]:
df
df2 =df1.copy()

for i in list(df2.columns[4:10]):
    df2[i]=(df2[i]-df2[i].min())/(df2[i].max()-df2[i].min())
df2=df2.drop(['score','类别'],axis=1)
df2
df2['score']=df2.英语+df2.体育+df2.军训+df2.数分+df2.高代+df2.解几
df2.score.describe()
bins=[df2.score.min()-1,3,4,df2.score.max()+1]
label=["一般","较好","优秀"]
df3=pd.cut(df2.score,bins,right=False, labels = label)
df2['类别']=df3
df2

,学号,班级,姓名,性别,英语,体育,军训,数分,高代,解几,score,类别
0,2308024241,23080242,成龙,男,0.64,0.812500,0.827957,0.000000,0.000000,0.410256,2.690713,一般
1,2308024244,23080242,周怡,女,0.24,0.947917,0.806452,0.184211,0.358209,0.000000,2.536788,一般
2,2308024251,23080242,张波,男,1.00,0.843750,0.806452,0.131579,0.328358,0.410256,3.520395,较好
3,2308024249,23080242,朱浩,男,0.20,0.520833,0.860215,0.842105,0.582090,0.692308,3.697551,较好
4,2308024219,23080242,封印,女,0.52,0.916667,0.989247,0.552632,0.358209,0.051282,3.388037,较好
5,2308024201,23080242,迟培,男,0.00,0.520833,0.956989,0.815789,0.791045,0.692308,3.776965,较好
6,2308024347,23080243,李华,女,0.28,0.635417,0.903226,0.552632,0.626866,0.871795,3.869935,较好
7,2308024307,23080243,陈田,男,0.64,0.822917,0.924731,0.763158,0.253731,0.641026,4.045563,优秀
8,2308024326,23080243,余皓,男,0.24,0.697917,0.913978,0.657895,0.567164,0.692308,3.769262,较好
9,2308024320,23080243,李嘉,女,0.08,0.000000,0.967742,0.526316,0.656716,0.846154,3.076928,较好
10,2308024342,23080243,李上初,男,0.64,0.937500,0.903226,0.526316,0.641791,0.410256,4.059089,优秀
11,2308024310,23080243,郭窦,女,0.76,0.697917,0.903226,0.631579,0.611940,0.897436,4.502098,优秀
12,2308024435,23080244,姜毅涛,男,0.68,0.739583,0.000000,0.552632,0.746269,0.820513,3.538996,较好
13,2308024432,23080244,赵宇,男,0.56,0.770833,0.946237,0.736842,0.701493,0.692308,4.407712,优秀
14,2308024446,23080244,周路,女,0.64,0.833333,0.000000,0.552632,0.761194,0.923077,3.710236,较好
15,2308024421,23080244,林建祥,男,0.48,0.750000,0.870968,0.605263,1.000000,0.794872,4.501103,优秀
16,2308024433,23080244,李大强,男,0.76,0.791667,0.827957,1.000000,0.701493,0.666667,4.747783,优秀
17,2308024428,23080244,李侧通,男,0.16,1.000000,0.978495,0.763158,0.552239,0.846154,4.300045,优秀
18,2308024402,23080244,王慧,女,0.52,0.770833,1.000000,0.789474,0.716418,0.794872,4.591597,优秀
19,2308024422,23080244,李晓亮,男,1.00,0.625000,0.913978,0.842105,0.731343,1.000000,5.112427,优秀

### 数据处理步骤总结：
1. 数据载入
2. 数据重复查找
3. 空数据查找填充
4. 处理数据中的空格
5. 查看列数据类型
6. 以0填充非int型数据

### 本章小结
pandas库，数据准备，数据处理。数据清洗和准备是最重要的
0. 导入库
    - import pandas as pd
    - import numpy as np
    - import matplotlib.pyplot as plt

1. 查看数据

    - 查看数据的头尾
        - df.head()
        - df.tail(3)
    - 显示索引、列和底层的Numpy数据
        - df.index
        - df.columns
        - df.values
    - 数据快速统计汇总
        - df.describe()
    - 对数据转置
        - df.T
    - 按轴排序
        - df.sort_index(axis=1, ascending=False)
    - 按值进行排序
        - df.sort_values(by='B')
        
2. 选择
    
    - 通过标签选择
        - 使用标签来获取一个交叉的区域
            - df.loc[date[0]]
        - 通过标签在多个轴上进行选择
            - df.loc[:,['A','B']]
        - 标签切片
            - df.loc['20130302':'20130405',['A','B']]
        - 对于返回的对象进行维度缩减
            - df.loc['20130302',['A','B']]
        - 获取一个标量
            - df.loc[dates[0],'A']
        - 快速访问一个标量
            - df.at[dates[0],'A']
    
    - 通过位置选择
        - 通过传递数值选择位置（行）
            - df.iloc[3]
        - 通过数值进行切片
            - df.iloc[3:5, 0:2]
        - 通过指定一个位置的列表进行位置选择
            - df.iloc[[1,2,4],[0,2]]
        - 对行进行切片
            - df.iloc[1:3,:]
        - 对列切片
            - df.iloc[:,1:3]
        - 获取特定值
            - df.iloc[3,5]
            - df.iat[1,1]
     
     - 布尔索引
        - 使用一个单独列的值来选择数据：
            - df[df.A>0]
        - 使用where
            - np.where(df>0)
        - 使用isin()方法来过滤：
            - df2 = df.copy()
            - df2['E']

In [ ]:
'''
本章小结

pandas库，数据准备，数据处理。数据清洗和准备是最重要的

    0. 导入库
        import pandas as pd
        import numpy as np
        import matplotlib.pyplot as plt

    1. 查看数据
        查看数据的头尾
            df.head()
            df.tail(3)
        显示索引、列和底层的Numpy数据
            df.index
            df.columns
            df.values
        数据快速统计汇总
            df.describe()
        对数据转置
            df.T
        按轴排序
            df.sort_index(axis=1, ascending=False)
        按值进行排序
            df.sort_values(by='B')

    2. 选择

        通过标签选择
            使用标签来获取一个交叉的区域
                df.loc[date[0]]
            通过标签在多个轴上进行选择
                df.loc[:,['A','B']]
            标签切片
                df.loc['20130302':'20130405',['A','B']]
            对于返回的对象进行维度缩减
                df.loc['20130302',['A','B']]
            获取一个标量
                df.loc[dates[0],'A']
            快速访问一个标量
                df.at[dates[0],'A']

        通过位置选择
            通过传递数值选择位置（行）
                df.iloc[3]
            通过数值进行切片
                df.iloc[3:5, 0:2]
            通过指定一个位置的列表进行位置选择
                df.iloc[[1,2,4],[0,2]]
            对行进行切片
                df.iloc[1:3,:]
            对列切片
                df.iloc[:,1:3]
            获取特定值
                df.iloc[3,5]
                df.iat[1,1]
            布尔索引
                使用一个单独列的值来选择数据：
                    df[df.A>0]
                使用where
                    np.where(df>0)
                使用isin()方法来过滤：
                    df2 = df.copy()
                    df2['E']=['one','one','two','three','four','five']
                    df2[df2[E].isin(['two','four'])]
        设置
            通过标签设置新的值
                df.at[dates[0],'A'] = 0
            通过位置设置新的值
                df.iat[0,1] = 0
            通过一个Numpy数组设置一组新值
                df.loc[:,'D']=np.array([5] * len(df))
    3.缺失值处理
        对指定轴上的索引增删改，并返回原始数据的一个备份
            df1= df.reindex(index=dates[0:4], columns=list(df.columns) + ['E'])
            df1.loc[dates[0]:dates[1],'E']= 1
        去掉包含缺失值的行（舍弃）
            df1.dropna(how='any')
        对缺失值进行填充
            df1.fillna(value=5)
        对数据进行布尔填充
            pd.isnull(df1)
    4. 相关操作
        统计
            描述性统计
                df.mean()
                df.mean(1)在纵轴
            对不同维度，需要对齐的对象进行操作
                s = pd.Series([1,3,5,np.nan,6,8], index=dates).shift(2)
                df.sub(s, axis ='index')
        对数据应用函数
            df.apply(np.cumsum)
            df.apply(lambda x : x.max9() - x.min())
        直方图
            s = pd.Series(np.random.randint(0,7,size=10))
            s.value_counts()
    5. 合并
        concat()
        df= pd.DataFrame(np.random.randn(10,4))
        pieces = [df[:3],df[3:7],df[7:]]
        pd.concat(pieces)
        
        join()
        left = pd.DataFrame({'key':['foo','foo'],'lval':[1,2]})
        right = pd.DataFrame({'key':['foo','foo'],'rval':[4,5]})
        pd.merge(left,right ,on ='key')
        
        append()
        df = pd.DataFrame(np.random.randn(8,4),
                            columns=list('ABCD'))
        s = df.iloc[3]
        df.append(s, ignore_index=True)
        
    6. 分组
        cut(数据数组，面元数组)# 数据分成几个部分，就成为几个面元

        
        
'''